language: go
go:
- '1.10'
script:
- make all
deploy:
  provider: releases
  api_key:
    secure: g0V3NxmSXpGs0c3iEA49rJtuKqeyOsjOZlzHuWt1MvWZjSgTaK++sQswtgp30L9Y1HakNh+AkugLB9S8xQ//kx6/+lOV74clN4mXmQ0YtJFqRtNV4ICpgZO+NsNPJwgVGJejhJN3m3Y5zseLGjBExghiwmHvidMEI+ne8u+mohZ/s6BN+nWxP6PlNumYpYbFqFFNybm0LhJzu2oA2ltOgJ7AIYg1kvmVovOceYaog00X5bSg58qvUXJm63RFolJrI+1IGpDPyguyV2VQg8PsXtFy0hoZ8Uk/OURZ5yBwf2OG7HBRpYvPl2fkiVCqkRzXySo5naxvBO2Cu3+8AqDrGhLxyi7j+2iUytVA+kkBmdJG9NktigocPo+pJ+JcFZlnRmkdCRC3/ujYNoi/4F/GaXrKzao4rAf/oi8wwQyI90Cmn1nMWgD8gkvv/sDIieimR2wH6xCeNkYRpbLnAgVc1Ic+3LHDq5i0oO2u1rW0p2lXKO+WofcSU5wywArL+pAGu5qGjDRBUxCznqCgAIXwonp0FyoM3yoXSU2TlvDe40wIzFQnSG6NgzCoWGmbe14j00alcJk8PtjUT6CxR8ure+TZmiGH7Fdsn2ZG8xJt4pA/burH5qK34/9DC1wlznVJUG1VX6pWE2qdujhaDAbWQs6jIpAliydd1X/ShLTKj24=
  file: email
  skip_cleanup: true
  on:
    repo: wrouesnel/emailcli
    tags: true
